name: Release

on:
  push:
    branch: main

jobs:
  build:
  
    permissions:
      contents: write
      issues: write
      pull-requests: write
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          
      - name: Create npm pack
        shell: bash
        run: npm pack

      - name: Install plugins
        shell: bash
        run: npm install @semantic-release/git @semantic-release/changelog conventional-changelog-conventionalcommits -D

      - name: Release
        shell: bash
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
